# frozen_string_literal: true

require 'rake/testtask'
require_relative 'src/application'

task default: :test

desc 'Run iTunes File Delimiter Replacer'
Rake::Task.define_task(:run_itunes_file_delimiter_replacer) do
  puts 'Provide the target extension of files whose delimiter you would like to make changes to(e.g., .m4a)'
  extension = $stdin.gets&.chomp&.strip

  puts 'Provide the delimiter you would like to replace the original one with(Default: `_`)'
  delimiter = $stdin.gets&.chomp&.strip

  puts 'Provide d(dry_run: default) to make sure what directories and files are to be delete first. Then, provide e(execution) if you would truly like to delete the files. This operation is cannot be undone, so be alert to your operation!'
  mode = $stdin.gets&.chomp&.strip

  params = { extension:, delimiter:, mode: }.reject { |_, value| value&.empty? }

  Application.run(**params)
end

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
