# frozen_string_literal: true

require 'rake/testtask'
require_relative 'lib/spreen_tracks'
require 'bundler/gem_helper'
Bundler::GemHelper.install_tasks
# Must come after install_tasks: the setter delegates to the instance that install_tasks creates.
Bundler::GemHelper.tag_prefix = 'ruby-' # rake release tags ruby-vX.Y.Z

task default: :test

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
