# frozen_string_literal: true

D = Steep::Diagnostic

target :app do
  check 'lib'
  check 'test'
  signature 'sig'

  library 'fileutils'
  library 'optparse'
  library 'minitest'

  configure_code_diagnostics(D::Ruby.default)
end
